export const packetNames = {
  common: {
    packetHeader: 'common.Packet',
  },
  gamePacket: {
    registerRequest: 'C2SRegisterRequest',
    registerResponse: 'S2CRegisterResponse',
    loginRequest: 'C2SLoginRequest',
    loginResponse: 'S2CLoginResponse',
    matchRequest: 'C2SMatchRequest',
    matchStartNotification: 'S2CMatchStartNotification',
    stateSyncNotification: 'S2CStateSyncNotification',
    towerPurchaseRequest: 'C2STowerPurchaseRequest',
    towerPurchaseResponse: 'S2CTowerPurchaseResponse',
    addEnemyTowerNotification: 'S2CAddEnemyTowerNotification',
    spawnMonsterRequest: 'C2SSpawnMonsterRequest',
    spawnMonsterResponse: 'S2CSpawnMonsterResponse',
    spawnEnemyMonsterNotification: 'S2CSpawnEnemyMonsterNotification',
    towerAttackRequest: 'C2STowerAttackRequest',
    enemyTowerAttackNotification: 'S2CEnemyTowerAttackNotification',
    monsterAttackBaseRequest: 'C2SMonsterAttackBaseRequest',
    updateBaseHpNotification: 'S2CUpdateBaseHPNotification',
    gameOverNotification: 'S2CGameOverNotification',
    gameEndRequest: 'C2SGameEndRequest',
    monsterDeathNotification: 'C2SMonsterDeathNotification',
    enemyMonsterDeathNotification: 'S2CEnemyMonsterDeathNotification',
  },
};
