export const packetNames = {
  common: {
    packetHeader: 'common.Packet',
  },
  gamePacket: {
    C2SRegisterRequest: 'gamePacket.C2SRegisterRequest',
    S2CRegisterResponse: 'gamePacket.S2CRegisterResponse',
    C2SLoginRequest: 'gamePacket.C2SLoginRequest',
    S2CLoginResponse: 'gamePacket.S2CLoginResponse',
    C2SMatchRequest: 'gamePacket.C2SMatchRequest',
    S2CMatchStartNotification: 'gamePacket.S2CMatchStartNotification',
    S2CStateSyncNotification: 'gamePacket.S2CStateSyncNotification',
    C2STowerPurchaseRequest: 'gamePacket.C2STowerPurchaseRequest',
    S2CTowerPurchaseResponse: 'gamePacket.S2CTowerPurchaseResponse',
    S2CAddEnemyTowerNotification: 'gamePacket.S2CAddEnemyTowerNotification',
    C2SSpawnMonsterRequest: 'gamePacket.C2SSpawnMonsterRequest',
    S2CSpawnMonsterResponse: 'gamePacket.S2CSpawnMonsterResponse',
    S2CSpawnEnemyMonsterNotification: 'gamePacket.S2CSpawnEnemyMonsterNotification',
    C2STowerAttackRequest: 'gamePacket.C2STowerAttackRequest',
    S2CEnemyTowerAttackNotification: 'gamePacket.S2CEnemyTowerAttackNotification',
    C2SMonsterAttackBaseRequest: 'gamePacket.C2SMonsterAttackBaseRequest',
    S2CUpdateBaseHPNotification: 'gamePacket.S2CUpdateBaseHPNotification',
    S2CGameOverNotification: 'gamePacket.S2CGameOverNotification',
    C2SGameEndRequest: 'gamePacket.C2SGameEndRequest',
    C2SMonsterDeathNotification: 'gamePacket.C2SMonsterDeathNotification',
    S2CEnemyMonsterDeathNotification: 'gamePacket.S2CEnemyMonsterDeathNotification',
    GamePacket: 'gamePacket.GamePacket',
  },
};
