export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  SPAWN_MONSTER_REQUEST: 11,
  SPAWN_MONSTER_RESPONSE: 12,
  SPAWN_ENEMY_MONSTER_NOTIFICATION: 13,
  MONSTER_ATTACK_BASE_REQUEST: 16,
  UPDATE_BASE_HP_NOTIFICATION: 17,
};
