export const ErrorCodes = {
  NONE: 0,
  UNKNOWN_ERROR: 1,
  INVALID_REQUEST: 2,
  AUTHENTICATION_FAILED: 3,
  PACKET_DECODE_ERROR: 4,
  SESSION_NOT_FOUND: 5,
  BASE_NOT_FOUND: 6,
  MONSTER_NOT_FOUND: 7,
};
